In [1]:
import os
os.getcwd()

'C:\\Users\\saras\\Documents\\Y4\\HonsProject\\notebooks'

In [2]:
import pandas as pd
import json
from sqlalchemy import create_engine

engine = create_engine("sqlite:///../data/names_results1.db")
df = pd.read_sql("SELECT * FROM names", engine)
df["full_countries_distribution"] = df["full_countries_distribution"].apply(json.loads)

df.head()

,name,full_countries_distribution,top_country,top_country_prob,strong_top_country,agreement_score,n_models_used,name_script,name_latin,eth_EastAsian,...,eth_Hispanic,eth_Italian,eth_Nordic,ethnicolr_race,langdetect_lang,langdetect_prob,hunspell_orig_known,hunspell_latin_known,pysc_orig_known,pysc_latin_known
0,A A,"{'Afghanistan': None, 'Albania': None, 'Algeri...",Bangladesh,0.329,0,NaN,0,Latin,A A,0.106898,...,0.070977,0.063327,0.154168,"GreaterAfrican,Muslim",hu,1.0000,0,0,0,0
1,A A A,"{'Afghanistan': None, 'Albania': None, 'Algeri...",Bangladesh,0.714,1,NaN,0,Latin,A A A,0.230757,...,0.053853,0.046734,0.116572,"Asian,GreaterEastAsian,EastAsian",hu,1.0000,0,0,0,0
2,A A Ron,"{'Afghanistan': None, 'Albania': None, 'Algeri...",United States,0.615,0,NaN,0,Latin,A A Ron,0.670941,...,0.016496,0.011205,0.015815,"Asian,GreaterEastAsian,EastAsian",hu,1.0000,0,0,0,0
3,A Abdiel,"{'Afghanistan': None, 'Albania': None, 'Algeri...",Panama,1.000,1,NaN,0,Latin,A Abdiel,0.010752,...,0.025052,0.021789,0.004987,"GreaterAfrican,Africans",de,0.7143,0,0,0,0
4,A Abera,"{'Afghanistan': None, 'Albania': None, 'Algeri...",Ethiopia,1.000,1,NaN,0,Latin,A Abera,0.044627,...,0.037988,0.097774,0.052131,"GreaterAfrican,Muslim",hu,0.7143,0,0,0,0

In [3]:
df2 = pd.read_sql("select count(*) from names where strong_top_country", engine)
df2.head()

   count(*)
0    339711

In [5]:
pd.read_sql("SELECT * FROM names WHERE name_script != 'Latin'", engine).head()

,name,full_countries_distribution,top_country,top_country_prob,strong_top_country,agreement_score,n_models_used,name_script,name_latin,eth_EastAsian,...,eth_Hispanic,eth_Italian,eth_Nordic,ethnicolr_race,langdetect_lang,langdetect_prob,hunspell_orig_known,hunspell_latin_known,pysc_orig_known,pysc_latin_known
0,[[,"{""Afghanistan"": null, ""Albania"": null, ""Algeri...",Morocco,0.881,1,NaN,0,Other,[[,NaN,...,NaN,NaN,NaN,None,None,NaN,0,0,0,0
1,Άβα,"{""Afghanistan"": null, ""Albania"": null, ""Algeri...",Greece,1.000,1,NaN,0,Greek,Ava,0.045876,...,0.033241,0.054120,0.007559,"GreaterAfrican,Muslim",el,1.0,0,1,0,0
2,Άγγελα,"{""Afghanistan"": null, ""Albania"": null, ""Algeri...",Cyprus,1.000,1,NaN,0,Greek,Aggela,0.020201,...,0.025209,0.055258,0.396450,"GreaterEuropean,WestEuropean,Nordic",el,1.0,0,0,0,0
3,Άγγελος,"{""Afghanistan"": null, ""Albania"": 0.008, ""Alger...",Greece,0.912,1,NaN,0,Greek,Aggelos,0.002790,...,0.094509,0.262897,0.042508,"GreaterEuropean,WestEuropean,Italian",el,1.0,0,0,0,0
4,Άγης,"{""Afghanistan"": null, ""Albania"": null, ""Algeri...",Greece,0.800,1,NaN,0,Greek,Agis,0.063292,...,0.038788,0.102621,0.128907,"GreaterAfrican,Muslim",el,1.0,0,0,0,0

In [7]:
pd.read_sql("SELECT * FROM names WHERE name_script = 'Other'", engine)

,name,full_countries_distribution,top_country,top_country_prob,strong_top_country,agreement_score,n_models_used,name_script,name_latin,eth_EastAsian,...,eth_Hispanic,eth_Italian,eth_Nordic,ethnicolr_race,langdetect_lang,langdetect_prob,hunspell_orig_known,hunspell_latin_known,pysc_orig_known,pysc_latin_known
0,[[,"{""Afghanistan"": null, ""Albania"": null, ""Algeri...",Morocco,0.881,1,None,0,Other,[[,None,...,None,None,None,None,None,None,0,0,0,0